### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by dvaldivia** [lucafmarques/rpchan#3]
Wouldn't it make more sense to wrap the type T into a common struct similar to Rust's `Result` so you either get a result or an error in the same struct and no separate error handling is needed, but it's on a per message basis

**Comment by lucafmarques** [comment]
First of all, thanks for contributing.

Well, Go doesn't really have sum-types like Rust does, so a `Result` in Go would just be a struct a value and an error, and I fail to see how that would remove error handling for the `RPChan.Send` and `RPChan.Close` methods.

Would you care to provide an example of what you mean?

**Comment by dvaldivia** [comment]
I was trying to see if the library could be used just like channels without caring if you are calling things remotely or locally, for example if there's a send channel that blocks until the message is successfully sent over the wire, we can truly use this as a replacement or wrapper to regular channels, and to do that if we need to handle errors in the receiving end, it feels more like calling a function than working with a regular channel

**Comment by lucafmarques** [comment]
I've made some breaking changes to the package that might align more with what you were proposing, but to be clear, it's not a `Result` struct.
